### ISSUE TITLE
Never checkin `node_modules` directory to the source control system

### ISSUE THREAD

**Issue by huan** [BUPT/api-gateway#12]
Please add `node_modules` to `.gitignore`, and remove `/node_modules` directory from this repository.

@BUPT/api-gateway

**Comment by linyimin0812** [comment]
I have added node_modules to .gitignore, and removed /node_modules directory from this repository.Thanks for Zhuohuan senior's advice.

**Comment by huan** [comment]
@lym152898 awesome!

Please close this issue after you believe you had resolved the problem.

Thank you very much!

**Comment by linyimin0812** [comment]
ok.
